FROM public.ecr.aws/lambda/python:3.12

RUN dnf update -y && \
    dnf install -y \
    gcc-c++ \
    java-17-amazon-corretto-headless \
    nodejs \
    golang && \
    dnf clean all


COPY lambda_function.py ${LAMBDA_TASK_ROOT}

CMD [ "lambda_function.handler" ]